package Colecciones.Mapas;

import java.util.Scanner;

public class DiccionarioApp {

    static Scanner read = new Scanner(System.in);

    static void main(String[] args) {

        int contador_aciertos = 0;
        int contador_preguntas = 0;
        int contador_errores = 0;

        Diccionario diccionario =  new Diccionario();

        diccionario.nuevoPar("Casa", "House");
        diccionario.nuevoPar("Gato", "Cat");
        diccionario.nuevoPar("Perro", "Dog");
        diccionario.nuevoPar("Mesa", "Table");
        diccionario.nuevoPar("Silla", "Chair");
        diccionario.nuevoPar("Libro", "Book");
        diccionario.nuevoPar("Puerta", "Door");
        diccionario.nuevoPar("Ventana", "Window");
        diccionario.nuevoPar("Coche", "Car");
        diccionario.nuevoPar("Camino", "Road");
        diccionario.nuevoPar("Cielo", "Sky");
        diccionario.nuevoPar("Tierra", "Earth");
        diccionario.nuevoPar("Agua", "Water");
        diccionario.nuevoPar("Fuego", "Fire");
        diccionario.nuevoPar("Aire", "Air");
        diccionario.nuevoPar("Sol", "Sun");
        diccionario.nuevoPar("Luna", "Moon");
        diccionario.nuevoPar("Estrella", "Star");
        diccionario.nuevoPar("Mar", "Sea");
        diccionario.nuevoPar("Rio", "River");
        diccionario.nuevoPar("Montaña", "Mountain");
        diccionario.nuevoPar("Bosque", "Forest");
        diccionario.nuevoPar("Árbol", "Tree");
        diccionario.nuevoPar("Flor", "Flower");
        diccionario.nuevoPar("Hierba", "Grass");
        diccionario.nuevoPar("Arena", "Sand");
        diccionario.nuevoPar("Playa", "Beach");
        diccionario.nuevoPar("Isla", "Island");
        diccionario.nuevoPar("Puente", "Bridge");
        diccionario.nuevoPar("Ciudad", "City");
        diccionario.nuevoPar("Pueblo", "Town");
        diccionario.nuevoPar("Barrio", "Neighborhood");
        diccionario.nuevoPar("Calle", "Street");
        diccionario.nuevoPar("Avenida", "Avenue");
        diccionario.nuevoPar("Plaza", "Square");
        diccionario.nuevoPar("Escuela", "School");
        diccionario.nuevoPar("Universidad", "University");
        diccionario.nuevoPar("Profesor", "Teacher");
        diccionario.nuevoPar("Alumno", "Student");
        diccionario.nuevoPar("Clase", "Class");
        diccionario.nuevoPar("Examen", "Exam");
        diccionario.nuevoPar("Respuesta", "Answer");
        diccionario.nuevoPar("Pregunta", "Question");
        diccionario.nuevoPar("Cuaderno", "Notebook");
        diccionario.nuevoPar("Lápiz", "Pencil");
        diccionario.nuevoPar("Bolígrafo", "Pen");
        diccionario.nuevoPar("Papel", "Paper");
        diccionario.nuevoPar("Mochila", "Backpack");
        diccionario.nuevoPar("Regla", "Ruler");
        diccionario.nuevoPar("Borrador", "Eraser");
        diccionario.nuevoPar("Pantalla", "Screen");
        diccionario.nuevoPar("Ordenador", "Computer");
        diccionario.nuevoPar("Teclado", "Keyboard");
        diccionario.nuevoPar("Ratón", "Mouse");
        diccionario.nuevoPar("Teléfono", "Phone");
        diccionario.nuevoPar("Internet", "Internet");
        diccionario.nuevoPar("Programa", "Program");
        diccionario.nuevoPar("Código", "Code");
        diccionario.nuevoPar("Lenguaje", "Language");
        diccionario.nuevoPar("Dato", "Data");
        diccionario.nuevoPar("Archivo", "File");
        diccionario.nuevoPar("Carpeta", "Folder");
        diccionario.nuevoPar("Servidor", "Server");
        diccionario.nuevoPar("Red", "Network");
        diccionario.nuevoPar("Usuario", "User");
        diccionario.nuevoPar("Contraseña", "Password");
        diccionario.nuevoPar("Acceso", "Access");
        diccionario.nuevoPar("Sistema", "System");
        diccionario.nuevoPar("Memoria", "Memory");
        diccionario.nuevoPar("Proceso", "Process");
        diccionario.nuevoPar("Entrada", "Input");
        diccionario.nuevoPar("Salida", "Output");
        diccionario.nuevoPar("Pantalla", "Display");
        diccionario.nuevoPar("Botón", "Button");
        diccionario.nuevoPar("Ventana", "Window");
        diccionario.nuevoPar("Aplicación", "Application");
        diccionario.nuevoPar("Juego", "Game");
        diccionario.nuevoPar("Nivel", "Level");
        diccionario.nuevoPar("Puntuación", "Score");
        diccionario.nuevoPar("Jugador", "Player");
        diccionario.nuevoPar("Equipo", "Team");
        diccionario.nuevoPar("Victoria", "Victory");
        diccionario.nuevoPar("Derrota", "Defeat");
        diccionario.nuevoPar("Empate", "Draw");
        diccionario.nuevoPar("Campo", "Field");
        diccionario.nuevoPar("Pelota", "Ball");
        diccionario.nuevoPar("Gol", "Goal");
        diccionario.nuevoPar("Árbitro", "Referee");
        diccionario.nuevoPar("Partido", "Match");
        diccionario.nuevoPar("Tiempo", "Time");
        diccionario.nuevoPar("Minuto", "Minute");
        diccionario.nuevoPar("Segundo", "Second");
        diccionario.nuevoPar("Hora", "Hour");
        diccionario.nuevoPar("Día", "Day");
        diccionario.nuevoPar("Semana", "Week");
        diccionario.nuevoPar("Mes", "Month");
        diccionario.nuevoPar("Año", "Year");
        diccionario.nuevoPar("Pasado", "Past");
        diccionario.nuevoPar("Presente", "Present");
        diccionario.nuevoPar("Futuro", "Future");
        diccionario.nuevoPar("Comida", "Food");
        diccionario.nuevoPar("Bebida", "Drink");
        diccionario.nuevoPar("Pan", "Bread");
        diccionario.nuevoPar("Leche", "Milk");
        diccionario.nuevoPar("Queso", "Cheese");
        diccionario.nuevoPar("Carne", "Meat");
        diccionario.nuevoPar("Pollo", "Chicken");
        diccionario.nuevoPar("Pescado", "Fish");
        diccionario.nuevoPar("Arroz", "Rice");
        diccionario.nuevoPar("Pasta", "Pasta");
        diccionario.nuevoPar("Sopa", "Soup");
        diccionario.nuevoPar("Ensalada", "Salad");
        diccionario.nuevoPar("Fruta", "Fruit");
        diccionario.nuevoPar("Manzana", "Apple");
        diccionario.nuevoPar("Plátano", "Banana");
        diccionario.nuevoPar("Naranja", "Orange");
        diccionario.nuevoPar("Fresa", "Strawberry");
        diccionario.nuevoPar("Uva", "Grape");
        diccionario.nuevoPar("Melón", "Melon");
        diccionario.nuevoPar("Sandía", "Watermelon");
        diccionario.nuevoPar("Azúcar", "Sugar");
        diccionario.nuevoPar("Sal", "Salt");
        diccionario.nuevoPar("Aceite", "Oil");
        diccionario.nuevoPar("Mantequilla", "Butter");
        diccionario.nuevoPar("Huevo", "Egg");
        diccionario.nuevoPar("Desayuno", "Breakfast");
        diccionario.nuevoPar("Almuerzo", "Lunch");
        diccionario.nuevoPar("Cena", "Dinner");
        diccionario.nuevoPar("Cuchara", "Spoon");
        diccionario.nuevoPar("Tenedor", "Fork");
        diccionario.nuevoPar("Cuchillo", "Knife");
        diccionario.nuevoPar("Plato", "Plate");
        diccionario.nuevoPar("Vaso", "Glass");
        diccionario.nuevoPar("Taza", "Cup");
        diccionario.nuevoPar("Botella", "Bottle");
        diccionario.nuevoPar("Restaurante", "Restaurant");
        diccionario.nuevoPar("Camarero", "Waiter");
        diccionario.nuevoPar("Cuenta", "Bill");
        diccionario.nuevoPar("Propina", "Tip");
        diccionario.nuevoPar("Mercado", "Market");
        diccionario.nuevoPar("Tienda", "Shop");
        diccionario.nuevoPar("Precio", "Price");
        diccionario.nuevoPar("Dinero", "Money");
        diccionario.nuevoPar("Moneda", "Coin");
        diccionario.nuevoPar("Billete", "Bill");
        diccionario.nuevoPar("Banco", "Bank");
        diccionario.nuevoPar("Compra", "Purchase");
        diccionario.nuevoPar("Venta", "Sale");
        diccionario.nuevoPar("Oferta", "Offer");
        diccionario.nuevoPar("Descuento", "Discount");
        diccionario.nuevoPar("Trabajo", "Work");
        diccionario.nuevoPar("Empleado", "Employee");
        diccionario.nuevoPar("Jefe", "Boss");
        diccionario.nuevoPar("Oficina", "Office");
        diccionario.nuevoPar("Empresa", "Company");
        diccionario.nuevoPar("Reunión", "Meeting");
        diccionario.nuevoPar("Proyecto", "Project");
        diccionario.nuevoPar("Contrato", "Contract");
        diccionario.nuevoPar("Salario", "Salary");
        diccionario.nuevoPar("Vacaciones", "Vacation");
        diccionario.nuevoPar("Descanso", "Rest");
        diccionario.nuevoPar("Viaje", "Trip");
        diccionario.nuevoPar("Hotel", "Hotel");
        diccionario.nuevoPar("Habitación", "Room");
        diccionario.nuevoPar("Llave", "Key");
        diccionario.nuevoPar("Reserva", "Reservation");
        diccionario.nuevoPar("Avión", "Plane");
        diccionario.nuevoPar("Aeropuerto", "Airport");
        diccionario.nuevoPar("Vuelo", "Flight");
        diccionario.nuevoPar("Maleta", "Suitcase");
        diccionario.nuevoPar("Pasaporte", "Passport");
        diccionario.nuevoPar("Billete", "Ticket");
        diccionario.nuevoPar("Tren", "Train");
        diccionario.nuevoPar("Estación", "Station");
        diccionario.nuevoPar("Metro", "Subway");
        diccionario.nuevoPar("Autobús", "Bus");
        diccionario.nuevoPar("Taxi", "Taxi");
        diccionario.nuevoPar("Conductor", "Driver");
        diccionario.nuevoPar("Pasajero", "Passenger");
        diccionario.nuevoPar("Mapa", "Map");
        diccionario.nuevoPar("Ruta", "Route");
        diccionario.nuevoPar("Dirección", "Direction");
        diccionario.nuevoPar("Norte", "North");
        diccionario.nuevoPar("Sur", "South");
        diccionario.nuevoPar("Este", "East");
        diccionario.nuevoPar("Oeste", "West");
        diccionario.nuevoPar("Izquierda", "Left");
        diccionario.nuevoPar("Derecha", "Right");
        diccionario.nuevoPar("Centro", "Center");
        diccionario.nuevoPar("Arriba", "Up");
        diccionario.nuevoPar("Abajo", "Down");
        diccionario.nuevoPar("Dentro", "Inside");
        diccionario.nuevoPar("Fuera", "Outside");
        diccionario.nuevoPar("Cerca", "Near");
        diccionario.nuevoPar("Lejos", "Far");
        diccionario.nuevoPar("Grande", "Big");
        diccionario.nuevoPar("Pequeño", "Small");
        diccionario.nuevoPar("Largo", "Long");
        diccionario.nuevoPar("Corto", "Short");
        diccionario.nuevoPar("Alto", "Tall");
        diccionario.nuevoPar("Bajo", "Low");
        diccionario.nuevoPar("Ancho", "Wide");
        diccionario.nuevoPar("Estrecho", "Narrow");
        diccionario.nuevoPar("Rápido", "Fast");
        diccionario.nuevoPar("Lento", "Slow");
        diccionario.nuevoPar("Fuerte", "Strong");
        diccionario.nuevoPar("Débil", "Weak");
        diccionario.nuevoPar("Nuevo", "New");
        diccionario.nuevoPar("Viejo", "Old");
        diccionario.nuevoPar("Joven", "Young");
        diccionario.nuevoPar("Antiguo", "Ancient");
        diccionario.nuevoPar("Bonito", "Beautiful");
        diccionario.nuevoPar("Feo", "Ugly");
        diccionario.nuevoPar("Claro", "Clear");
        diccionario.nuevoPar("Oscuro", "Dark");
        diccionario.nuevoPar("Frío", "Cold");
        diccionario.nuevoPar("Caliente", "Hot");
        diccionario.nuevoPar("Tibio", "Warm");
        diccionario.nuevoPar("Seco", "Dry");
        diccionario.nuevoPar("Húmedo", "Wet");
        diccionario.nuevoPar("Limpio", "Clean");
        diccionario.nuevoPar("Sucio", "Dirty");
        diccionario.nuevoPar("Abierto", "Open");
        diccionario.nuevoPar("Cerrado", "Closed");
        diccionario.nuevoPar("Fácil", "Easy");
        diccionario.nuevoPar("Difícil", "Difficult");
        diccionario.nuevoPar("Correcto", "Correct");
        diccionario.nuevoPar("Incorrecto", "Incorrect");
        diccionario.nuevoPar("Verdadero", "True");
        diccionario.nuevoPar("Falso", "False");
        diccionario.nuevoPar("Amigo", "Friend");
        diccionario.nuevoPar("Amiga", "FemaleFriend");
        diccionario.nuevoPar("Familia", "Family");
        diccionario.nuevoPar("Padre", "Father");
        diccionario.nuevoPar("Madre", "Mother");
        diccionario.nuevoPar("Hermano", "Brother");
        diccionario.nuevoPar("Hermana", "Sister");
        diccionario.nuevoPar("Hijo", "Son");
        diccionario.nuevoPar("Hija", "Daughter");
        diccionario.nuevoPar("Abuelo", "Grandfather");
        diccionario.nuevoPar("Abuela", "Grandmother");
        diccionario.nuevoPar("Tío", "Uncle");
        diccionario.nuevoPar("Tía", "Aunt");
        diccionario.nuevoPar("Primo", "Cousin");
        diccionario.nuevoPar("Prima", "FemaleCousin");
        diccionario.nuevoPar("Bebé", "Baby");
        diccionario.nuevoPar("Niño", "Child");
        diccionario.nuevoPar("Niña", "Girl");
        diccionario.nuevoPar("Hombre", "Man");
        diccionario.nuevoPar("Mujer", "Woman");
        diccionario.nuevoPar("Persona", "Person");
        diccionario.nuevoPar("Gente", "People");
        diccionario.nuevoPar("Nombre", "Name");
        diccionario.nuevoPar("Apellido", "Surname");
        diccionario.nuevoPar("Edad", "Age");
        diccionario.nuevoPar("Cumpleaños", "Birthday");
        diccionario.nuevoPar("Regalo", "Gift");
        diccionario.nuevoPar("Fiesta", "Party");
        diccionario.nuevoPar("Celebración", "Celebration");
        diccionario.nuevoPar("Invitado", "Guest");
        diccionario.nuevoPar("Música", "Music");
        diccionario.nuevoPar("Canción", "Song");
        diccionario.nuevoPar("Baile", "Dance");
        diccionario.nuevoPar("Película", "Movie");
        diccionario.nuevoPar("Actor", "Actor");
        diccionario.nuevoPar("Actriz", "Actress");
        diccionario.nuevoPar("Director", "Director");
        diccionario.nuevoPar("Escena", "Scene");
        diccionario.nuevoPar("Historia", "Story");
        diccionario.nuevoPar("Aventura", "Adventure");
        diccionario.nuevoPar("Misterio", "Mystery");
        diccionario.nuevoPar("Terror", "Horror");
        diccionario.nuevoPar("Comedia", "Comedy");
        diccionario.nuevoPar("Drama", "Drama");
        diccionario.nuevoPar("Serie", "Series");
        diccionario.nuevoPar("Capítulo", "Episode");
        diccionario.nuevoPar("Temporada", "Season");
        diccionario.nuevoPar("Pantalla", "Screen");
        diccionario.nuevoPar("Televisión", "Television");
        diccionario.nuevoPar("Radio", "Radio");
        diccionario.nuevoPar("Noticias", "News");
        diccionario.nuevoPar("Periódico", "Newspaper");
        diccionario.nuevoPar("Revista", "Magazine");
        diccionario.nuevoPar("Artículo", "Article");
        diccionario.nuevoPar("Fotografía", "Photograph");
        diccionario.nuevoPar("Imagen", "Image");
        diccionario.nuevoPar("Color", "Color");
        diccionario.nuevoPar("Rojo", "Red");
        diccionario.nuevoPar("Azul", "Blue");
        diccionario.nuevoPar("Verde", "Green");
        diccionario.nuevoPar("Amarillo", "Yellow");
        diccionario.nuevoPar("Negro", "Black");
        diccionario.nuevoPar("Blanco", "White");
        diccionario.nuevoPar("Gris", "Gray");
        diccionario.nuevoPar("Rosa", "Pink");
        diccionario.nuevoPar("Morado", "Purple");
        diccionario.nuevoPar("Marrón", "Brown");
        diccionario.nuevoPar("Dorado", "Golden");
        diccionario.nuevoPar("Plateado", "Silver");
        diccionario.nuevoPar("Brillante", "Bright");
        diccionario.nuevoPar("Opaco", "Dull");
        diccionario.nuevoPar("Suave", "Soft");
        diccionario.nuevoPar("Duro", "Hard");
        diccionario.nuevoPar("Pesado", "Heavy");
        diccionario.nuevoPar("Ligero", "Light");
        diccionario.nuevoPar("Delgado", "Thin");
        diccionario.nuevoPar("Grueso", "Thick");
        diccionario.nuevoPar("Recto", "Straight");
        diccionario.nuevoPar("Curvo", "Curved");
        diccionario.nuevoPar("Redondo", "Round");
        diccionario.nuevoPar("Cuadrado", "Square");
        diccionario.nuevoPar("Triángulo", "Triangle");
        diccionario.nuevoPar("Línea", "Line");
        diccionario.nuevoPar("Punto", "Point");
        diccionario.nuevoPar("Número", "Number");
        diccionario.nuevoPar("Cero", "Zero");
        diccionario.nuevoPar("Uno", "One");
        diccionario.nuevoPar("Dos", "Two");
        diccionario.nuevoPar("Tres", "Three");
        diccionario.nuevoPar("Cuatro", "Four");
        diccionario.nuevoPar("Cinco", "Five");
        diccionario.nuevoPar("Seis", "Six");
        diccionario.nuevoPar("Siete", "Seven");
        diccionario.nuevoPar("Ocho", "Eight");
        diccionario.nuevoPar("Nueve", "Nine");
        diccionario.nuevoPar("Diez", "Ten");
        diccionario.nuevoPar("Once", "Eleven");
        diccionario.nuevoPar("Doce", "Twelve");
        diccionario.nuevoPar("Trece", "Thirteen");
        diccionario.nuevoPar("Catorce", "Fourteen");
        diccionario.nuevoPar("Quince", "Fifteen");
        diccionario.nuevoPar("Dieciséis", "Sixteen");
        diccionario.nuevoPar("Diecisiete", "Seventeen");
        diccionario.nuevoPar("Dieciocho", "Eighteen");
        diccionario.nuevoPar("Diecinueve", "Nineteen");
        diccionario.nuevoPar("Veinte", "Twenty");
        diccionario.nuevoPar("Treinta", "Thirty");
        diccionario.nuevoPar("Cuarenta", "Forty");
        diccionario.nuevoPar("Cincuenta", "Fifty");
        diccionario.nuevoPar("Sesenta", "Sixty");
        diccionario.nuevoPar("Setenta", "Seventy");
        diccionario.nuevoPar("Ochenta", "Eighty");
        diccionario.nuevoPar("Noventa", "Ninety");
        diccionario.nuevoPar("Cien", "Hundred");

        diccionario.rellenar_claves_restantes();

        while (!diccionario.getClaves_restantes().isEmpty()){

            String palabra = diccionario.palabraAleatoria();

            System.out.println(palabra + " : " + diccionario.primeraLetraTraduccion(palabra) + "...");
            System.out.println("Indique la respuesta : ");
            String respuesta = read.nextLine();

            if (respuesta.equals(diccionario.getDiccionario().get(palabra))){

                System.out.println("¡CORRECTO!");
                contador_aciertos++;
                contador_preguntas++;


            } else if (respuesta.equals("fin")) {

                break;

            }else {

                System.out.println("¡ERORR!, La respuesta correcta es " + diccionario.getDiccionario().get(palabra));
                contador_preguntas++;
                contador_errores++;

            }

        }

        System.out.println("FIN DEL PROGRAMA");
        System.out.println("Total preguntas : " + contador_preguntas);
        System.out.println("Total aciertos : " + contador_aciertos);
        System.out.println("Total errores : " + contador_errores);
        System.out.println("Aciertos : " + ((contador_aciertos * 100)/contador_preguntas) + "%");

    }

}
